server:
  port: 8082
#eureka:
#  client:
#    registerWithEureka: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: learning-code
          uri: lb://learning-code
          predicates:
            - Path=/learning-code/**
          filters:
            - RewritePath=/learning-code/(?<path>.*), /$\{path}
